name: custom viz
on:  
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish Nerdpack
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # - name: "Setup - Terraform CLI"
      #   uses: hashicorp/setup-terraform@v1
       
      - name: Install NR1 CLI
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Configure NR1 CLI API key
        run: nr1 profiles:add --name account-slug --api-key ${{secrets.NEW_RELIC_API_KEY}} --region us 

      # - name: Get Package Version
      #   id: get-version
      #   run: |
      #     PACKAGE_VERSION=$(cat package.json | jq -r .version)
      #     echo $PACKAGE_VERSION

      - name: Update Nerdpack Version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          echo "current version : $CURRENT_VERSION"
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "new version : $NEW_VERSION"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > tmp.json && mv tmp.json package.json
          git config --global user.email "aman39mit@gmail.com"
          git config --global user.name "aman39mit"
          git add package.json
          git commit -m "Bump version to $NEW_VERSION"
          git push origin main

        # PACKAGE_VERSION=$(cat package.json | jq -r .version)
        # echo $PACKAGE_VERSION
        # NEW_VERSION=$(echo "$PACKAGE_VERSION" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        # echo "Updating Nerdpack version to $NEW_VERSION"
        # jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > tmp.json
        # mv tmp.json package.json
        # run: npm version patch -m "Bump version to %s"
      
      - name: Publish Nerdpack
        run: nr1 nerdpack:publish
        id: publish
        continue-on-error: false
      - name: Check if publish was successful
        run: |
          if [ ${{ steps.publish.exit_code }} -eq 0 ]; then
            echo "Nerdpack published successfully"
          else
            echo "Nerdpack publish failed"
          fi
      
      - name: Subscribe Nerdpack
        run: nr1 nerdpack:subscribe

        
